---
title: "Домашнее задание №1"
subtitle: "OTUS: Математика для Data Science"
author: "Андрей Павлюченко"
date: "21.12.2021"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
  html_document:
    df_print: paged
---

## Часть 1

### 1. Задача 1

Найдите решение системы (1):
```{=latex}
\begin{equation}
    \begin{cases}
      x_1 + x_2 – x_3 = 0\\
      2x_1 + x_3 = 0
    \end{cases}
\end{equation}
```

**Ответ:**
<!-- можно \boxed{…} -->
\[\begin{aligned}
\begin{pmatrix}
  1 & 1 & -1 & \vrule & 0\\
  2 & 0 & 1  & \vrule & 0
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2) - 2\times(1)}
\begin{pmatrix}
  1 & 1 & -1 & \vrule & 0\\
  0 & -2 & 3 & \vrule & 0
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2) \div -2}
\begin{pmatrix}
  1 & 1 & -1   & \vrule & 0\\
  0 & 1 & -1.5 & \vrule & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1) - (2)}
\begin{pmatrix}
  1 & 0 & 0.5  & \vrule & 0\\
  0 & 1 & -1.5 & \vrule & 0
\end{pmatrix}
\end{aligned}\]

Матрица приведена к ступенчатому виду. Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3
\end{pmatrix}
= c_3 \times
\begin{pmatrix}
  -0.5\\
  1.5\\
  1
\end{pmatrix}
\end{aligned}$

### 2. Задача 2

Найдите решение системы (2):
```{=latex}
\begin{equation}
    \begin{cases}
      2x_1 + 2x_2 – x_3 + x_4 = 0\\
      -x_1 + x_2 - x_3 + x_4 = 0\\
      x_1 + 3x_2 - 2x_3 + 2x_4 = 0
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  2 & 2 & -1 & 1 &  \vrule & 0\\
  -1 & 1 & -1 & 1 & \vrule & 0\\
  1 & 3 & -2 & 2 &  \vrule & 0
\end{pmatrix}
\xrightarrow[{(3) \leftarrow (3) - (1)}]{(3) \leftarrow (3) - (2)}
\begin{pmatrix}
  2 & 2 & -1 & 1 &  \vrule & 0\\
  -1 & 1 & -1 & 1 & \vrule & 0\\
  0 & 0 & 0 & 0 &   \vrule & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftrightarrow (2)}
\begin{pmatrix}
  -1 & 1 & -1 & 1 & \vrule & 0\\
  2 & 2 & -1 & 1 &  \vrule & 0
\end{pmatrix}\\
\xrightarrow[{(1) \leftarrow (1) - \frac{1}{4}\times(2)}]{(2) \leftarrow (2) + 2\times(1)}
\begin{pmatrix}
  -1 & 0 & -\frac{1}{4} & \frac{1}{4} & \vrule & 0\\
  0 & 4 & -3 & 3 &  \vrule & 0
\end{pmatrix}
\xrightarrow[{(2)\leftarrow(2)\div4}]{(1) \leftarrow -1\times(1)}
\begin{pmatrix}
  1 & 0 & 0.25 & -0.25 & \vrule & 0\\
  0 & 1 & -0.75 & 0.75 &  \vrule & 0
\end{pmatrix}
\end{aligned}\]

Матрица приведена к ступенчатому виду. Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3\\
  x_4
\end{pmatrix}
= c_3 \times
\begin{pmatrix}
  -0.25\\
  0.75\\
  1\\
  0
\end{pmatrix}
+ c_4 \times
\begin{pmatrix}
  0.25\\
  -0.75\\
  0\\
  1
\end{pmatrix}
\end{aligned}$

## Часть 2

Найдите общее решение неоднородных систем линейных уравнений (3:7)

### 1.

```{=latex}
\begin{equation}
    \begin{cases}
      5x_1 - 5x_2 + 4x_3 = 0\\
      3x_1 - x_2 + 3x_3 = 0\\
      x_1 + 7x_2 - x_3 = 0
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  5 & -5 & 4 &  \vrule & 0\\
  3 & -1 & 3 &  \vrule & 0\\
  1 & 7 & -1 &  \vrule & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftrightarrow (3)}
\begin{pmatrix}
  1 & 7 & -1 &  \vrule & 0\\
  3 & -1 & 3 &  \vrule & 0\\
  5 & -5 & 4 &  \vrule & 0
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3) - 2\times(2)]{(3) \leftarrow (3) + (1)}
\begin{pmatrix}
  1 & 7 & -1 &  \vrule & 0\\
  3 & -1 & 3 &  \vrule & 0\\
  0 & 4 & -3 &  \vrule & 0
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2) - 3\times(1)}\\
\begin{pmatrix}
  1 & 7 & -1  &  \vrule & 0\\
  0 & -22 & 6 &  \vrule & 0\\
  0 & 4 & -3  &  \vrule & 0
\end{pmatrix}
\xrightarrow[(2) \leftarrow (2)\div2]{(2) \leftarrow (2)+6\times(3)}
\begin{pmatrix}
  1 & 7 & -1 &  \vrule & 0\\
  0 & 1 & -6 &  \vrule & 0\\
  0 & 4 & -3 &  \vrule & 0
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)\div21]{(3) \leftarrow (3)-4\times(2)}
\begin{pmatrix}
  1 & 7 & -1 &  \vrule & 0\\
  0 & 1 & -6 &  \vrule & 0\\
  0 & 0 & 1 &  \vrule & 0
\end{pmatrix}
\xrightarrow[(1) \leftarrow (1)+(3)]{(2) \leftarrow (2)+6\times(3)}\\
\begin{pmatrix}
  1 & 7 & 0 &  \vrule & 0\\
  0 & 1 & 0 &  \vrule & 0\\
  0 & 0 & 1 &  \vrule & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1)-7\times(2)}
\begin{pmatrix}
  1 & 0 & 0 &  \vrule & 0\\
  0 & 1 & 0 &  \vrule & 0\\
  0 & 0 & 1 &  \vrule & 0
\end{pmatrix}
\end{aligned}\]

Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3
\end{pmatrix}
= \begin{pmatrix}
  0\\
  0\\
  0
\end{pmatrix}
\end{aligned}$

### 2.

```{=latex}
\begin{equation}
    \begin{cases}
      -4x_1 + x_2 = 1\\
      x_1 + 3x_2 = -6
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  -4 & 1 & \vrule & 1\\
  1 & 3  & \vrule & -6
\end{pmatrix}
\xrightarrow[]{(1) \leftrightarrow (2)}
\begin{pmatrix}
  1 & 3  & \vrule & -6\\
  -4 & 1 & \vrule & 1
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)+4\times(1)}
\begin{pmatrix}
  1 & 3  & \vrule & -6\\
  0 & 13 & \vrule & -23
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)\div13}
\begin{pmatrix}
  1 & 3  & \vrule & -6\\
  0 & 1 & \vrule & -\frac{23}{13}
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow 3\times(2)}\\
\begin{pmatrix}
  1 & 0  & \vrule & _{(\frac{-78}{13} - \frac{-69}{13})} -\frac{9}{13}\\
  0 & 1 & \vrule & -1\frac{10}{13}
\end{pmatrix}
\end{aligned}\]

Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2
\end{pmatrix}
= \begin{pmatrix}
  -\frac{9}{13}\\
  -1\frac{10}{13}
\end{pmatrix}
\end{aligned}$

### 3.

```{=latex}
\begin{equation}
    \begin{cases}
      3x_1 + 2x_2 - x_3 = 4\\
      2x_1 - x_2 + 5x_3 = 23\\
      x_1 + 7x_2  - x_3 = 5
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  3 & 2 & -1 & \vrule & 4\\
  2 & -1 & 5 & \vrule & 23\\
  1 & 7 & -1 & \vrule & 5
\end{pmatrix}
\xrightarrow[]{(1) \leftrightarrow (3)}
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  2 & -1 & 5 & \vrule & 23\\
  3 & 2 & -1 & \vrule & 4
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)-(1)]{(3) \leftarrow (3)-(2)}
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  2 & -1 & 5 & \vrule & 23\\
  0 & -4 & -5 & \vrule & -24
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)-2\times(1)}\\
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  0 & -15 & 7 & \vrule & 13\\
  0 & -4 & -5 & \vrule & -24
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)-4\times(3)}
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  0 & 1 & 27 & \vrule & 109\\
  0 & -4 & -5 & \vrule & -24
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3)+4\times(2)}
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  0 & 1 & 27 & \vrule & 109\\
  0 & 0 & 103 & \vrule & 412
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3)\div103}\\
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  0 & 1 & 27 & \vrule & 109\\
  0 & 0 & 1 & \vrule & 4
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2) -27\times(3)}
\begin{pmatrix}
  1 & 7 & -1 & \vrule & 5\\
  0 & 1 & 0 & \vrule & 1\\
  0 & 0 & 1 & \vrule & 4
\end{pmatrix}
\xrightarrow[(1) \leftarrow (1)-7\times(2)]{(1) \leftarrow (1)+(3)}
\begin{pmatrix}
  1 & 0 & 0 & \vrule & 2\\
  0 & 1 & 0 & \vrule & 1\\
  0 & 0 & 1 & \vrule & 4
\end{pmatrix}
\end{aligned}\]

Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3
\end{pmatrix}
= \begin{pmatrix}
  2\\
  1\\
  4
\end{pmatrix}
\end{aligned}$

### 4.

```{=latex}
\begin{equation}
    \begin{cases}
      2x_1 + 3x_2 + 5x_3 = 1\\
      -4x_1 + x_2 + 2x_3 = -7\\
      x_1 + 7x_2  + 14x_3 = -5
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  2 & 3  & 5 & \vrule & 1\\
  -4 & 1 & 2 & \vrule & -7\\
  1 & 7 & 14 & \vrule & -5
\end{pmatrix}
\xrightarrow[]{(1) \leftrightarrow (3)}
\begin{pmatrix}
  1 & 7 & 14 & \vrule & -5\\
  -4 & 1 & 2 & \vrule & -7\\
  2 & 3 & 5  & \vrule & 1
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)-2\times(1)]{(2) \leftarrow (2) + 2\times(3)}
\begin{pmatrix}
  1 & 7 & 14 & \vrule & -5\\
  0 & 7 & 12 & \vrule & -5\\
  0 & -11 & -23  & \vrule & 11
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1) -(2)}\\
\begin{pmatrix}
  1 & 0 & 2 & \vrule & 0\\
  0 & 7 & 12 & \vrule & -5\\
  0 & -11 & -23  & \vrule & 11
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)\div7}
\begin{pmatrix}
  1 & 0 & 2 & \vrule & 0\\
  0 & 1 & 1\frac{5}{7} & \vrule & -\frac{5}{7}\\
  0 & -11 & -23  & \vrule & 11
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3) + 11\times(2)}\\
\begin{pmatrix}
  1 & 0 & 2 & \vrule & 0\\
  0 & 1 & \frac{12}{7} & \vrule & -\frac{5}{7}\\
  0 & 0 & _{(-\frac{161}{7}+\frac{132}{7})}-\frac{29}{7}  & \vrule &
    _{(\frac{77}{7}-\frac{55}{7})}\frac{22}{7}
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3)\div-4\frac{1}{7}}
\begin{pmatrix}
  1 & 0 & 2 & \vrule & 0\\
  0 & 1 & 1\frac{5}{7} & \vrule & -\frac{5}{7}\\
  0 & 0 & 1  & \vrule &
    _{(\frac{\frac{22}{\cancel{7}}}{-\frac{29}{\cancel{7}}})}-\frac{22}{29}
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)-1\frac{5}{7}\times(3)}\\
\begin{pmatrix}
  1 & 0 & 2 & \vrule & 0\\
  0 & 1 & 0 & \vrule &
    _{(-\frac{5}{7}-(\frac{12}{7}\times\frac{22}{29}) =
    \frac{264}{203}-\frac{145}{203})}\frac{17}{29}\\
  0 & 0 & 1  & \vrule & -\frac{22}{29}
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1)-2\times(3)}
\begin{pmatrix}
  1 & 0 & 0 & \vrule & \frac{44}{29}\\
  0 & 1 & 0 & \vrule & \frac{17}{29}\\
  0 & 0 & 1  & \vrule & -\frac{22}{29}
\end{pmatrix}
\end{aligned}\]

Запишем ответ:

$\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3
\end{pmatrix}
= \begin{pmatrix}
  1\frac{15}{29}\\
  \frac{17}{29}\\
  -\frac{22}{29}
\end{pmatrix}
\end{aligned}$

### 5.

```{=latex}
\begin{equation}
    \begin{cases}
      x_1 - x_2 + x_3 - x_4 + x_5 = 2\\
      2x_1 - 3x_2 + 2x_3 + 2x_5 = 4\\
      3x_1 - 4x_2 + 3x_3 - x_4 + 3x_5 = 6
    \end{cases}
\end{equation}
```

**Ответ:**

\[\begin{aligned}
\begin{pmatrix}
  1 & -1 & 1 & -1 & 1 & \vrule & 2\\
  2 & -3 & 2 & 0 & 2  & \vrule & 4\\
  3 & -4 & 3 & -1 & 3 & \vrule & 6
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)-3\times(1)]{(2) \leftarrow (2)-2\times(1)}
\begin{pmatrix}
  1 & -1 & 1 & -1 & 1 & \vrule & 2\\
  0 & -1 & 0 & 2 & 0  & \vrule & 0\\
  0 & -1 & 0 & 2 & 0  & \vrule & 0
\end{pmatrix}
\xrightarrow[]{(2) \leftarrow (2)\times-1}
\begin{pmatrix}
  1 & -1 & 1 & -1 & 1 & \vrule & 2\\
  0 & 1 & 0 & -2 & 0  & \vrule & 0\\
  0 & -1 & 0 & 2 & 0  & \vrule & 0
\end{pmatrix}\\
\xrightarrow[(3) \leftarrow (3)+(2)]{(1) \leftarrow (1)+(2)}
\begin{pmatrix}
  1 & 0 & 1 & -3 & 1 & \vrule & 2\\
  0 & 1 & 0 & -2 & 0 & \vrule & 0\\
  0 & 0 & 0 & 0 & 0  & \vrule & 0
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)+(2)]{(1) \leftarrow (1)+(2)}
\begin{pmatrix}
  1 & 0 & 1 & -3 & 1 & \vrule & 2\\
  0 & 1 & 0 & -2 & 0 & \vrule & 0
\end{pmatrix}
\end{aligned}\]

Матрица приведена к ступенчатому виду. Запишем ответ:

\[\begin{aligned}
\begin{pmatrix}
  x_1\\
  x_2\\
  x_3\\
  x_4\\
  x_5
\end{pmatrix}
= \begin{pmatrix}
  2\\
  0\\
  0\\
  0\\
  0
\end{pmatrix}
+c_3 \times
\begin{pmatrix}
  -1\\
  0\\
  1\\
  0\\
  0
\end{pmatrix}
+c_4 \times
\begin{pmatrix}
  3\\
  2\\
  0\\
  1\\
  0
\end{pmatrix}
+c_5 \times
\begin{pmatrix}
  -1\\
  0\\
  0\\
  0\\
  1
\end{pmatrix}
\end{aligned}\]