---
title: "Домашнее задание №2"
subtitle: "OTUS: Математика для Data Science"
author: "Андрей Павлюченко"
date: "28.12.2021"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
  html_document:
    df_print: paged
---

## Задача 1

Перемножение матриц:

#### а)
Задана матрица $A = \begin{pmatrix}7&1&-1\\1&-3&5\\-6&2&-2\end{pmatrix}$ и матрица $B = \begin{pmatrix}-9&-6&2\\0&-5&5\\0&5&-7\end{pmatrix}$. Найдите $AB$.

**Ответ:**
\[\begin{aligned}
AB=
\begin{pmatrix}
  7×-9 + 1×0 - 1×0  & 7×-6 + 1×-5 - 1×5 & 7×2 + 1×5 - 1×-7\\
  1×-9 - 3×0 + 5×0  & 1×-6 - 3×-5 + 5×5 & 1×2 - 3×5 + 5×-7\\
  -6×-9 + 2×0 - 2×0 & -6×-6 + 2×-5 -2×5 & -6×2 + 2×5 - 2×-7
\end{pmatrix}
=\\=
\begin{pmatrix}
  -63 + 0 - 0  & -42 - 5 - 5 & 14 + 5 + 7\\
  -9 - 0 + 0  & -6 + 15 + 25 & 2 - 15 - 35\\
  54 + 0 - 0 & 36 - 10 - 10 & -12 + 10 + 14
\end{pmatrix}
=
\begin{pmatrix}
  -63 & -52 & 26\\
  -9  & 34  & -48\\
  54  & 16  & 12
\end{pmatrix}
\end{aligned}\]

#### б)
Задана матрица $A = \begin{pmatrix}-9&5&2\\-8&-3&4\\-5&8&-8\end{pmatrix}$ и матрица $B = \begin{pmatrix}1&-5&1\\7&3&1\\-2&4&7\end{pmatrix}$. Найдите $AB$.

**Ответ:**
\[\begin{aligned}
AB=
\begin{pmatrix}
  -9×1 + 5×7 + 2×-2  & -9×-5 + 5×3 + 2×4 & -9×1 + 5×1 + 2×7\\
  -8×1 - 3×7 + 4×-2  & -8×-5 - 3×3 + 4×4 & -8×1 - 3×1 + 4×7\\
  -5×1 + 8×7 - 8×-2  & -5×-5 + 8×3 - 8×4 & -5×1 + 8×1 - 8×7
\end{pmatrix}
=\\=
\begin{pmatrix}
  -9 + 35 - 4  & 45 + 15 + 8 & -9 + 5 + 14\\
  -8 - 21 - 8  & 40 - 9 + 16 & -8 - 3 + 28\\
  -5 + 56 +16 & 25 + 24 -32 & -5 + 8 -56
\end{pmatrix}
=
\begin{pmatrix}
  22  & 68 & 10\\
  -37 & 47 & 17\\
  67  & 17 & -53
\end{pmatrix}
\end{aligned}\]

#### в)
Задана матрица $A = \begin{pmatrix}0&-4&-1\\-2&2&7\\4&6&9\end{pmatrix}$ и вектор $\vec{b} = \begin{pmatrix}2\\9\\0\end{pmatrix}$. Найдите $A\vec{b}$.

**Ответ (посчитаем, как линейную комбинацию):**
\[\begin{aligned}
A\vec{b}=
2×
\begin{pmatrix}
  0\\
  -2\\
  4
\end{pmatrix}
+ 9×
\begin{pmatrix}
  -4\\
  2\\
  6
\end{pmatrix}
+ 0×
\begin{pmatrix}
  -1\\
  7\\
  9
\end{pmatrix} =
\begin{pmatrix}
  0 - 36\\
  -4 + 18\\
  8 +54
\end{pmatrix} =
\begin{pmatrix}
  -36\\
  14\\
  62
\end{pmatrix}
\end{aligned}\]

## Задача 2

Найдите ранг матриц:

#### а)
$\begin{pmatrix}4&2&3\\5&2&1\\9&4&4\end{pmatrix}$

\[\begin{aligned}
\begin{pmatrix}
  4 & 2 & 3\\
  5 & 2 & 1\\
  9 & 4 & 4
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)-(2)]{(3) \leftarrow (3)-(1)}
\begin{pmatrix}
  4 & 2 & 3\\
  5 & 2 & 1\\
  0 & 0 & 0
\end{pmatrix}
\xrightarrow[(1) \leftarrow (1)-(2)]{(1) \leftrightarrow (2)}
\begin{pmatrix}
  1 & 0 & -2\\
  4 & 2 & 3\\
  0 & 0 & 0
\end{pmatrix}
\xrightarrow[(2) \leftarrow (2)\div2]{(2) \leftarrow (2)-4×1}
\begin{pmatrix}
  1 & 0 & -2\\
  0 & 1 & 5,5\\
  0 & 0 & 0
\end{pmatrix}
\end{aligned}\]

Ответ: $rkA = 2$

#### б)
$\begin{pmatrix}3&2&1&5\\6&4&3&7\\9&6&5&9\\3&2&0&8\end{pmatrix}$

\[\begin{aligned}
\begin{pmatrix}
  3 & 2 & 1 & 5\\
  6 & 4 & 3 & 7\\
  9 & 6 & 5 & 9\\
  3 & 2 & 0 & 8
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)-3×(1)]{(4) \leftarrow (4)-(1)}
\begin{pmatrix}
  3 & 2 & 1 & 5\\
  6 & 4 & 3 & 7\\
  0 & 0 & 2 & -6\\
  0 & 0 & -1 & 3
\end{pmatrix}
\xrightarrow[(1) \leftarrow (1)\div3]{(2) \leftarrow (2)-2×(1)}
\begin{pmatrix}
  1 & \frac{2}{3} & \frac{1}{3} & 1\frac{2}{3}\\
  0 & 0 & 1 & -3\\
  0 & 0 & 2 & -6\\
  0 & 0 & -1 & 3
\end{pmatrix}
\xrightarrow[(3) \leftarrow (3)\div2]{(4) \leftarrow (4)+(2)}\\
\begin{pmatrix}
  1 & \frac{2}{3} & \frac{1}{3} & 1\frac{2}{3}\\
  0 & 0 & 1 & -3\\
  0 & 0 & 1 & -3\\
  0 & 0 & 0 & 0
\end{pmatrix}
\xrightarrow[(2) \leftarrow (2)\div-3]{(3) \leftarrow (3)-(2)}
\begin{pmatrix}
  1 & \frac{2}{3} & \frac{1}{3} & 1\frac{2}{3}\\
  0 & 0 & -\frac{1}{3} & 1\\
  0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1)+(2)}
\begin{pmatrix}
  1 & \frac{2}{3} & 0 & 2\frac{2}{3}\\
  0 & 0 & -\frac{1}{3} & 1\\
  0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0
\end{pmatrix}
\end{aligned}\]

Ответ: $rkA = 2$

#### в)
$\begin{pmatrix}1&2&1&1\\0&1&1&1\\1&3&2&2\end{pmatrix}$

\[\begin{aligned}
\begin{pmatrix}
  1 & 2 & 1 & 1\\
  0 & 1 & 1 & 1\\
  1 & 3 & 2 & 2
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3)-(1)}
\begin{pmatrix}
  1 & 2 & 1 & 1\\
  0 & 1 & 1 & 1\\
  0 & 1 & 1 & 1
\end{pmatrix}
\xrightarrow[]{(3) \leftarrow (3)-(2)}
\begin{pmatrix}
  1 & 2 & 1 & 1\\
  0 & 1 & 1 & 1\\
  0 & 0 & 0 & 0
\end{pmatrix}
\xrightarrow[]{(1) \leftarrow (1)-(2)}
\begin{pmatrix}
  1 & 1 & 0 & 0\\
  0 & 1 & 1 & 1\\
  0 & 0 & 0 & 0
\end{pmatrix}
\end{aligned}\]

Ответ: $rkA = 2$

## Задача 3

Найдите значение определителя:

#### а)
$\begin{vmatrix}-3&7&4\\2&-1&2\\3&7&-3\end{vmatrix}$

**Ответ:**

\[\begin{aligned}
-3(-1×-3 - 2×7) - 7(2×-3 - 2×3) + 4(2×7 - -1×3)=\\
=-3×-11 - 7×-12 + 4×17 = 33 + 84 + 68 = 185
\end{aligned}\]

#### б)
$\begin{vmatrix}-1&0&2\\-10&-7&4\\-3&-3&2\end{vmatrix}$

**Ответ:**

\[\begin{aligned}
-1(-7×2 - 4×-3) - 0 + 2(-10×-3 - -7×-3)=-1×-2 - 0 + 2×9 = 2 + 18 = 20
\end{aligned}\]

#### в)
$\begin{vmatrix}4&-2&1\\-5&0&-1\\-7&2&7\end{vmatrix}$

**Ответ:**

\[\begin{aligned}
4(0+2) - -2(-5×7 - 7) + 1(-5×2 - 0)=8 - -2×-42 -10 = 8 -84 -10 = -86
\end{aligned}\]

#### г)
$\begin{vmatrix}7&-4&-10&3&1\\7&-9&2&-6&-2\\-3&-8&3&-7&-7\\7&8&-4&2&-8\\0&5&-12&9&3\end{vmatrix}$

**Ответ:**

Матрица вырожденная: $r_1 = r_2 + r_5$

$detA = 0$