---
title: "Домашнее задание №3"
subtitle: "OTUS: Математика для Data Science"
author: "Андрей Павлюченко"
date: "26.06.2022"
# R.I.P. Lex Plotnikoff
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
  html_document:
    df_print: paged
---

## Задача 1

Найдите определитель и собственные значения матриц:

#### а)

$A = \begin{pmatrix}4&-3&-3\\1&2&1\\1&1&2\end{pmatrix}$

**Ответ:**

1)  $detA = 4(2×2 - 1×1) - 1(-3×2 - -3×1) + 1(-3×1 - -3×2) = \\=4(4-1) - 1(-6 + 3) + 1(-3+6)=4×3 - 1(-3) + 1×3 = 12 + 3 + 3 = 18$

2)  $\begin{vmatrix}4-\lambda&-3&-3\\1&2-\lambda&1\\1&1&2-\lambda\end{vmatrix} = 0$

  > $(4-\lambda)((2-\lambda)^2 - 1) - 1(-3(2-\lambda) - -3×1) + 1(-3×1 - -3(2-\lambda))=0\\*$
  >  $(4-\lambda)(4-4\lambda+\lambda^2-1)-(-6+3\lambda+3)+(-3-(-6+3\lambda))=0\\*$
  >  $(4-\lambda)(\lambda^2-4\lambda+3) - (3\lambda-3) + (-3\lambda+3) = 0\\*$
  >  $(4\lambda^2-16\lambda+12-\lambda^3+4\lambda^2-3\lambda)-3\lambda+3-3\lambda+3=0\\*$
  >  $-\lambda^3+8\lambda^2-25\lambda+18=0\\*$
  >  $\lambda^3-8\lambda^2+25\lambda-18=0\\*$
  >  $(\lambda-1)(\lambda^2-7\lambda+18)=0\\*$
    
  > Тогда: $(\lambda-1)=0; \lambda_1=1\\*$

  > Уравнение ($\lambda^2-7\lambda+18=0$) не имеет действительных корней.

  > Ответ: $\lambda_1=1$

#### б)

$A = \begin{pmatrix}2&-1&0\\-1&2&0\\1&-1&1\end{pmatrix}$

**Ответ:**

1)  $detA = 0(-1^2 - 2×1) - 0(-1×2 - -1) + 1(2×2 - (-1×-1)) = \\=4 - (-1)^2 = 4-1 = 3$

2)  $\begin{vmatrix}2-\lambda&-1&0\\-1&2-\lambda&0\\1&-1&1-\lambda\end{vmatrix} = 0$

  > $(1-\lambda)((2-\lambda)^2 - (-1)^2)=0\\*$
  > $(1-\lambda)((2-\lambda)^2 - 1)=0\\*$
  > $(1-\lambda)(4-4\lambda+\lambda^2-1)=0\\*$
  > $(1-\lambda)(\lambda^2-4\lambda+3)=0\\*$
  > $(1-\lambda)((\lambda-1)(\lambda-3))=0\\*$

  > Ответ: $\lambda_1=3$; $\lambda_2=1$; $\lambda_3=1$

#### в)

$A = \begin{pmatrix}5&-1&-1\\0&4&-1\\0&-1&4\end{pmatrix}$

**Ответ:**

1)  $detA = 5(4^2 - (-1)^2) - 0 + 0 = 5(16-1) = 5×15 = 75$

2)  $\begin{vmatrix}5-\lambda&-1&-1\\0&4-\lambda&-1\\0&-1&4-\lambda\end{vmatrix} = 0$

  > $(5-\lambda)((4-\lambda)^2 - (-1)^2)=0\\*$
  > $(5-\lambda)((4-\lambda)^2 - 1)=0\\*$
  > $(5-\lambda)(16-8\lambda+\lambda^2-1)=0\\*$
  > $(5-\lambda)(\lambda^2-8\lambda+15)=0\\*$
  > $(5-\lambda)((\lambda-5)(\lambda-3))=0\\*$

  > Ответ: $\lambda_1=5$; $\lambda_2=5$; $\lambda_3=3$

## Задача 2

Диагонализируйте следующие матрицы:

#### а)

$A = \begin{pmatrix}7&-4&-2\\-2&5&-2\\0&0&9\end{pmatrix}$

**Ответ:**

1) Собственные значения:

$\begin{vmatrix}7-\lambda&-4&-2\\-2&5-\lambda&-2\\0&0&9-\lambda\end{vmatrix} = 0$

  > $0 - 0 + (9-\lambda)((5-\lambda)(7-\lambda)-8)=0\\*$
  > $(9-\lambda)(35-12\lambda+\lambda^2-8)=0\\*$
  > $(9-\lambda)(\lambda^2-12\lambda+27)=0\\*$
  > $(9-\lambda)((\lambda-9)(\lambda-3))=0\\*$
  
  > $\lambda_1=9$; $\lambda_2=9$; $\lambda_3=3$

2) Собственные векторы:

  > Для $\lambda=9$:

$\begin{aligned}
\begin{pmatrix}
  -2 & -4 & -2 & \vrule & 0\\*
  -2 & -4 & -2 & \vrule & 0\\*
   0 &  0 &  0 & \vrule & 0
\end{pmatrix}
\xrightarrow[{(1) \leftarrow (1) \div -2}]{(2) \leftarrow (2) - (1)}
\begin{pmatrix}
  1 & 2 & 1 & \vrule & 0\\*
  0 & 0 & 0 & \vrule & 0\\*
  0 & 0 & 0 & \vrule & 0
\end{pmatrix}
\end{aligned}$

  > Данному уравнению удовлетворяют векторы

$\begin{aligned}
\vec{v_1} = \alpha
\begin{pmatrix}
  2\\*
  -1\\*
  0
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$
и
$\begin{aligned}
\vec{v_2} = \alpha
\begin{pmatrix}
  -1\\*
  -2\\*
  5
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$

> Для $\lambda=3$:

$\begin{aligned}
\begin{pmatrix}
  4  & -4 & -2 & \vrule & 0\\*
  -2 & 2  & -2 & \vrule & 0\\*
  0  &  0 &  6 & \vrule & 0
\end{pmatrix}
\xrightarrow[{(3) \leftarrow (3) \div 6}]{(1) \leftarrow (1) \div 4}
\begin{pmatrix}
  1 & -1 & -\frac{1}{2} & \vrule & 0\\*
  -2 & 2 & -2           & \vrule & 0\\*
  0 & 0  & 1            & \vrule & 0
\end{pmatrix}
\xrightarrow[{}]{(2) \leftarrow (2) + 2×(1)}
\begin{pmatrix}
  1 & -1 & -\frac{1}{2} & \vrule & 0\\*
  0 & 0  & -3           & \vrule & 0\\*
  0 & 0  & 1            & \vrule & 0
\end{pmatrix}
\xrightarrow[{}]{(2) \leftarrow (2) \div -3}\\
\begin{pmatrix}
  1 & -1 & -\frac{1}{2} & \vrule & 0\\*
  0 & 0  & 1            & \vrule & 0\\*
  0 & 0  & 1            & \vrule & 0
\end{pmatrix}
\xrightarrow[{(1) \leftarrow (1) + (2) \div 2}]{(3) \leftarrow (3) - (2)}
\begin{pmatrix}
  1 & -1 & 0 & \vrule & 0\\*
  0 & 0  & 1 & \vrule & 0\\*
  0 & 0  & 0 & \vrule & 0
\end{pmatrix}
\end{aligned}$

  > Данному уравнению удовлетворяет вектор

$\begin{aligned}
\vec{v_3} = \alpha
\begin{pmatrix}
  1\\*
  1\\*
  0
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$

  > Собственный базис
  $Q = \begin{pmatrix}
    2  & -1 & 1 \\*
    -1 & -2 & 1\\*
    0  & 5  & 0
  \end{pmatrix}$
  
  > Диагональная матрица
  $\Lambda = \begin{pmatrix}
    9 & 0 & 0 \\*
    0 & 9 & 0 \\*
    0 & 0 & 3
  \end{pmatrix}$
  
  > Найдем $Q^{-1}$
  
\[\begin{aligned}
\begin{pmatrix}
  2  & -1 & 1 & \vrule & 1 & 0 & 0\\*
  -1 & -2 & 1 & \vrule & 0 & 1 & 0\\*
  0  &  5 & 0 & \vrule & 0 & 0 & 1
\end{pmatrix}
\xrightarrow[{(3) \leftrightarrow (2)}]{(1) \leftarrow (1) \div 2}
\begin{pmatrix}
  1  & -\frac{1}{2} & \frac{1}{2} & \vrule & \frac{1}{2} & 0 & 0\\*
  0  &  5 & 0 & \vrule & 0 & 0 & 1\\*
  -1 & -2 & 1 & \vrule & 0 & 1 & 0
\end{pmatrix}
\xrightarrow[{}]{(3) \leftarrow (3) + (1)}
\begin{pmatrix}
  1  & -\frac{1}{2} & \frac{1}{2} & \vrule & \frac{1}{2} & 0 & 0\\*
  0  &  5 & 0 & \vrule & 0 & 0 & 1\\*
  0 & -2\frac{1}{2} & 1\frac{1}{2} & \vrule & \frac{1}{2} & 1 & 0
\end{pmatrix}\\
\xrightarrow[{}]{(3) \leftarrow (3) + (2) \div 2}
\begin{pmatrix}
  1  & -\frac{1}{2} & \frac{1}{2} & \vrule & \frac{1}{2} & 0 & 0\\*
  0  &  5 & 0 & \vrule & 0 & 0 & 1\\*
  0 & 0 & 1\frac{1}{2} & \vrule & \frac{1}{2} & 1 & \frac{1}{2}
\end{pmatrix}
\xrightarrow[{(3) \leftarrow (3) \div 1,5}]{(2) \leftarrow (2) \div 5}
\begin{pmatrix}
  1  & -\frac{1}{2} & \frac{1}{2} & \vrule & \frac{1}{2} & 0 & 0\\*
  0  &  1 & 0 & \vrule & 0 & 0 & \frac{1}{5}\\*
  0 & 0 & 1 & \vrule & \frac{1}{3} & \frac{2}{3} & \frac{1}{3}
\end{pmatrix}
\xrightarrow[{}]{(1) \leftarrow 1 - (3) \div 2}\\
\begin{pmatrix}
  1  & -\frac{1}{2} & 0 & \vrule & \frac{1}{3} & -\frac{1}{3} & -\frac{1}{6}\\*
  0  &  1 & 0 & \vrule & 0 & 0 & \frac{1}{5}\\*
  0 & 0 & 1 & \vrule & \frac{1}{3} & \frac{2}{3} & \frac{1}{3}
\end{pmatrix}
\xrightarrow[{}]{(1) \leftarrow 1 + (2) \div 2}
\begin{pmatrix}
  1  & 0 & 0 & \vrule & \frac{1}{3} & -\frac{1}{3} & -\frac{1}{15}\\*
  0  &  1 & 0 & \vrule & 0 & 0 & \frac{1}{5}\\*
  0 & 0 & 1 & \vrule & \frac{1}{3} & \frac{2}{3} & \frac{1}{3}
\end{pmatrix}
\end{aligned}\]

  > $Q^{-1} = \begin{pmatrix}
    \frac{1}{3} & -\frac{1}{3} & -\frac{1}{15}\\*
    0 & 0 & \frac{1}{5}\\*
    \frac{1}{3} & \frac{2}{3} & \frac{1}{3}
  \end{pmatrix}$
  
  > Ответ: $A = Q \Lambda Q^{-1}$

\[\begin{pmatrix}7&-4&-2\\-2&5&-2\\0&0&9\end{pmatrix}=
\begin{pmatrix}
  2  & -1 & 1 \\*
  -1 & -2 & 1 \\*
  0  &  5 & 0
\end{pmatrix}
\begin{pmatrix}
  9 & 0 & 0 \\*
  0 & 9 & 0 \\*
  0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
  \frac{1}{3} & -\frac{1}{3} & -\frac{1}{15}\\*
  0           &  0           &  \frac{1}{5}\\*
  \frac{1}{3} &  \frac{2}{3} & \frac{1}{3}
\end{pmatrix}\]

#### б)

$A = \begin{pmatrix}3&0&0\\1&2&-1\\1&-1&2\end{pmatrix}$

**Ответ:**

1) Собственные значения:

$\begin{vmatrix}3-\lambda&0&0\\1&2\lambda&-1\\1&-1&2-\lambda\end{vmatrix} = 0$

  > $(3-\lambda)((2-\lambda)^2-1) - 0 + 0 =0\\*$
  > $(3-\lambda)(4-4\lambda+\lambda^2-1)=0\\*$
  > $(3-\lambda)(\lambda^2-4\lambda+3)=0\\*$
  > $(3-\lambda)((\lambda-3)(\lambda-1))=0\\*$
  
  > $\lambda_1=3$; $\lambda_2=3$; $\lambda_3=1$

2) Собственные векторы:

  > Для $\lambda=3$:
  
$\begin{aligned}
\begin{pmatrix}
  0 &  0 &  0 & \vrule & 0\\*
  1 & -1 & -1 & \vrule & 0\\*
  1 & -1 & -1 & \vrule & 0
\end{pmatrix}
\xrightarrow[{}]{(1) \leftrightarrow (3)}
\begin{pmatrix}
  1 & -1 & -1 & \vrule & 0\\*
  1 & -1 & -1 & \vrule & 0\\*
  0 &  0 &  0 & \vrule & 0
\end{pmatrix}
\xrightarrow[{}]{(2) \leftarrow (2)-(1)}
\begin{pmatrix}
  1 & -1 & -1 & \vrule & 0\\*
  0 &  0 &  0 & \vrule & 0\\*
  0 &  0 &  0 & \vrule & 0
\end{pmatrix}
\end{aligned}$

> Данному уравнению удовлетворяет множество векторов $\vec{v} = \begin{pmatrix}v_1\\v_2\\v_3\end{pmatrix} \in \mathbb{R^3}$, для котрых также верно $v_1 = v_2 + v_3$

> Пусть

$\begin{aligned}
\vec{v_1} = \alpha
\begin{pmatrix}
  2\\*
  1\\*
  1
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$

> Для $\lambda=1$:
  
$\begin{aligned}
\begin{pmatrix}
  2 &  0 &  0 & \vrule & 0\\*
  1 &  1 & -1 & \vrule & 0\\*
  1 & -1 &  1 & \vrule & 0
\end{pmatrix}
\xrightarrow[{(3) \leftarrow (3)-(2)}]{(1) \leftarrow (1) \div 2}
\begin{pmatrix}
  1 &  0 &  0 & \vrule & 0\\*
  1 &  1 & -1 & \vrule & 0\\*
  0 & -2 &  2 & \vrule & 0
\end{pmatrix}
\xrightarrow[{}]{(2) \leftarrow (2)-(1)}
\begin{pmatrix}
  1 &  0 &  0 & \vrule & 0\\*
  0 &  1 & -1 & \vrule & 0\\*
  0 & -2 &  2 & \vrule & 0
\end{pmatrix}\\
\xrightarrow[{}]{(3) \leftarrow (3)+2\times(1)}
\begin{pmatrix}
  1 & 0 &  0 & \vrule & 0\\*
  0 & 1 & -1 & \vrule & 0\\*
  0 & 0 &  0 & \vrule & 0
\end{pmatrix}
\end{aligned}$

> Данному уравнению удовлетворяет вектор

$\begin{aligned}
\vec{v_3} = \alpha
\begin{pmatrix}
  0\\*
  1\\*
  1
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$

> Воспользуемся тем, что $\vec{v_1} \in \mathbb{R^3}, \vec{v_3} \in \mathbb{R^3}$: найдем ортогональный им $\vec{v_2}$ как их векторное произведение: $\vec{v_2} = $\vec{v_1} \times $\vec{v_3}$

$\begin{aligned}
\begin{pmatrix}
  2\\*
  1\\*
  1
\end{pmatrix}
\times
\begin{pmatrix}
  0\\*
  1\\*
  1
\end{pmatrix} =
\begin{pmatrix}
  1×1-1×1\\*
  1×0-2×1\\*
  2×1-1×0
\end{pmatrix} =
\begin{pmatrix}
  0\\*
  -2\\*
  2
\end{pmatrix}
\end{aligned}$

> $\begin{pmatrix}0\\*-2\\*2\end{pmatrix}$ удовлетворяет уравнению $v_1 = v_2 + v_3$ (см. выше), т. е. также является собственным вектором $A$ с собственным значением 3:

$\begin{aligned}
\vec{v_2} = \alpha
\begin{pmatrix}
  0\\*
  -2\\*
  2
\end{pmatrix}
\end{aligned}, \alpha \in \mathbb{R}$

> Собственный базис
  $Q = \begin{pmatrix}
    2 &  0 & 0 \\*
    1 & -2 & 1\\*
    1 &  2 & 1
  \end{pmatrix}$
  
  > Диагональная матрица
  $\Lambda = \begin{pmatrix}
    3 & 0 & 0 \\*
    0 & 3 & 0 \\*
    0 & 0 & 1
  \end{pmatrix}$
  
  > Найдем $Q^{-1}$